// 美術館ごとの音声ガイド設定（各美術館は10作品）
export const MUSEUM_GUIDES = {
  1: [
    {
      id: 1,
      title: "作品1：現代アートの傑作",
      description: "この作品はあなたの好みに基づいて選ばれました。現代アートの世界をお楽しみください。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 2,
      title: "作品2：色彩の詩",
      description: "色彩の美しさが織りなす世界。この作品があなたの心に何を語りかけるかをお聴きください。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 3,
      title: "作品3：形態と空間",
      description: "空間を支配する形態。その深い意味をご紹介します。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 4,
      title: "作品4：光と影の共演",
      description: "光と影が生み出す、劇的な表現の世界へようこそ。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 5,
      title: "作品5：感情の流れ",
      description: "芸術家の感情が直接表現された、感動的な作品です。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 6,
      title: "作品6：素材の語り部",
      description: "素材そのものが語る物語。その真意に耳を傾けてください。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 7,
      title: "作品7：動きの静止",
      description: "時間を止めた瞬間。その躍動感をお感じください。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 8,
      title: "作品8：構成の美学",
      description: "完璧に計算された構成がもたらす、美の法則。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 9,
      title: "作品9：象徴と意味",
      description: "象徴に隠された深い意味。その謎をひもときます。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 10,
      title: "作品10：未来への扉",
      description: "芸術が開く新しい世界への入口。この先に何が待つかご一緒にお探しください。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
  ],
  2: [
    {
      id: 1,
      title: "作品1：伝統の継承",
      description: "日本の伝統美術の輝き。古き時代から今へと続く美の系譜をご紹介します。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 2,
      title: "作品2：技法の極致",
      description: "職人の手による完璧な技法。その精度と美しさをお楽しみください。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 3,
      title: "作品3：彩色の調べ",
      description: "伝統色彩が織りなす、日本美術ならではの色合いの世界。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 4,
      title: "作品4：精神性の表現",
      description: "日本の精神文化が表現された、深い内面の世界。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 5,
      title: "作品5：自然との対話",
      description: "自然を題材にした美しい作品。人間と自然の関係を描きます。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 6,
      title: "作品6：意匠の美",
      description: "細部に宿る意匠の美しさ。その設計思想をご紹介します。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 7,
      title: "作品7：時代を映す鏡",
      description: "その時代の文化や思想を映す、歴史の証人としての作品。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 8,
      title: "作品8：禅の美学",
      description: "引き算の美学。シンプルに秘められた深い禅の世界。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 9,
      title: "作品9：物語性",
      description: "物語を持つ作品。その背景にある物語をお聴きください。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 10,
      title: "作品10：永遠の美",
      description: "時代を超えて愛され続ける、永遠の美しさ。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
  ],
  3: [
    {
      id: 1,
      title: "作品1：近代への扉",
      description: "伝統から近代へ移行する時代の傑作。その転換点をご紹介します。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 2,
      title: "作品2：洋風の融合",
      description: "西洋美術と日本の伝統が融合した、ユニークな表現。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 3,
      title: "作品3：光の実験",
      description: "光と色の科学的な研究。その発見の過程をお楽しみください。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 4,
      title: "作品4：個性の主張",
      description: "個人の表現が尊重される時代の息吹。芸術家の自由意志が表現されています。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 5,
      title: "作品5：都市の息吹",
      description: "急速に発展する都市の活力。その躍動感をお感じください。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 6,
      title: "作品6：浪漫主義",
      description: "感情を優先する浪漫主義の表現。その情熱をお伝えします。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 7,
      title: "作品7：風景の詩",
      description: "風景を詩的に表現した作品。その世界観にお浸りください。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 8,
      title: "作品8：人間賛歌",
      description: "人間の美しさや尊厳を讃える作品。その力強さをお楽しみください。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 9,
      title: "作品9：実験的表現",
      description: "新しい表現方法への挑戦。その大胆さをご欣賞ください。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 10,
      title: "作品10：時代の結晶",
      description: "近代美術の成熟を象徴する傑作。その完成度をご堪能ください。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
  ],
  4: [
    {
      id: 1,
      title: "作品1：古典への敬意",
      description: "古典美術を敬い、その価値を継承する作品。その尊厳をお感じください。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 2,
      title: "作品2：色彩のハーモニー",
      description: "調和した色彩が作り出す、音楽的な美しさ。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 3,
      title: "作品3：構造の秩序",
      description: "複雑な構造を秩序立てて表現。その論理性をご堪能ください。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 4,
      title: "作品4：題材への向き合い方",
      description: "題材と真摯に向き合った、その精神性が伝わる作品。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 5,
      title: "作品5：細部への拘り",
      description: "細部にこだわり抜いた職人仕事。その完成度をお賞賛ください。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 6,
      title: "作品6：精緻な表現",
      description: "精緻で繊細な表現技法。その卓越さをご鑑賞ください。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 7,
      title: "作品7：歴史の証言",
      description: "歴史の一場面を記録した、貴重なドキュメント。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 8,
      title: "作品8：感情の共鳴",
      description: "観者の感情に深く共鳴する表現。その感動をお共有ください。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 9,
      title: "作品9：意図の明確さ",
      description: "芸術家の意図が明確に伝わる作品。その構想をお知りください。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 10,
      title: "作品10：完成の美",
      description: "芸術的完成を極めた傑作。その高みに至った作品をご尊敬ください。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
  ],
  5: [
    {
      id: 1,
      title: "作品1：アジアの心",
      description: "アジア各地の文化が交差する地点での創造。その多様性をお感じください。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 2,
      title: "作品2：現代への挑戦",
      description: "伝統を受け継ぎながら現代に挑む表現。その革新性をお堪能ください。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 3,
      title: "作品3：文化交流",
      description: "異文化との融合が生み出す、新しい美の形。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 4,
      title: "作品4：社会への眼差し",
      description: "社会的課題に向き合う、現代的なメッセージ。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 5,
      title: "作品5：多様性の表現",
      description: "様々な視点が共存する表現。その包括性をお尊重ください。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 6,
      title: "作品6：新世代の声",
      description: "新しい世代の芸術家による、フレッシュな表現。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 7,
      title: "作品7：技術と芸術",
      description: "最新技術と芸術が共鳴する作品。その未来性をお感じください。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 8,
      title: "作品8：地域への根差し",
      description: "地域の文化に根ざしながら、世界へと発信する作品。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 9,
      title: "作品9：対話の場",
      description: "観者との対話を生み出す、インタラクティブな表現。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 10,
      title: "作品10：未来への希望",
      description: "アジアの可能性を示唆する、希望に満ちた作品。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
  ],
  6: [
    {
      id: 1,
      title: "作品1：西洋美術の始まり",
      description: "ルネッサンスから現代へ。西洋美術の壮大な歴史をご紹介します。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 2,
      title: "作品2：古典の完成形",
      description: "ルネッサンスの理想が結晶した傑作。その美しさをお尊敬ください。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 3,
      title: "作品3：人体の美",
      description: "人体を究極に美しく表現した作品。その理想美をお堪能ください。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 4,
      title: "作品4：宗教美術の精華",
      description: "信仰心が表現された、精神性の高い作品。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 5,
      title: "作品5：遠近法の発見",
      description: "空間表現の革新。遠近法が生み出す奥行きをお感じください。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 6,
      title: "作品6：色彩革命",
      description: "色彩の可能性を広げた革新的な作品。その豊かさをお鑑賞ください。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 7,
      title: "作品7：歴史画の傑作",
      description: "歴史的出来事を劇的に表現した傑作。その迫力をお楽しみください。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 8,
      title: "作品8：心理の深さ",
      description: "登場人物の心理が深く描写された、人間描写の最高傑作。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 9,
      title: "作品9：自然の讃歌",
      description: "自然の雄大さと美しさを讃える作品。その威厳をお感じください。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
    {
      id: 10,
      title: "作品10：永遠の傑作",
      description: "時代を超えて愛され続ける西洋美術の最高峰。その価値をお堪能ください。",
      imageUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/image/222222.jpg",
      audioUrl: "https://storage.cloud.google.com/4th_hackathon_akakura_work/audio/jp/sample.mp4",
    },
  ],
};
